name: GitOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      ECR_REPOSITORY: gitops-app
      IMAGE_TAG: latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t gitops-app .

    - name: Tag Docker Image
      run: |
        docker tag gitops-app:latest \
        ${{ steps.login-ecr.outputs.registry }}/gitops-app:latest

    - name: Push Docker Image
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/gitops-app:latest

    - name: Update Helm Chart Image Tag
      run: |
        sed -i 's/tag:.*/tag: latest/' gitops-chart/values.yaml

    - name: Commit Updated Helm Values
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        git add gitops-chart/values.yaml
        git commit -m "Updated image tag automatically" || echo "No changes to commit"

        git push
